version: '3'

tasks:
  install-desktop:
    cmds:
    - task: update
    - task: cli-dependencies
    - task: desktop-dependencies
    - task: clean
    - task: reboot
  install-cli:
    cmds:
    - task: update
    - task: cli-dependencies
    - task: clean
    - task: reboot
  update:
    cmds:
      - apt update
      - apt dist-upgrade -y --allow-downgrades
  cli-dependencies:
    cmds:
      - apt update
      - apt install -y --allow-downgrades rsync ffmpeg lm-sensors net-tools nano nmap lsof htop telnet iputils-ping
  desktop-dependencies:
    cmds:
      - apt update
      - apt install -y --allow-downgrades vlc mpv
  clean:
    cmds:
      - apt autoremove -y
      - apt autoclean
  reboot:
    cmds:
      - reboot
