version: '3'

tasks:
  install:
    cmds:
    - task: update
    - task: dependencies
  update:
    cmds:
      - apt update
      - apt dist-upgrade -y --allow-downgrades
  dependencies:
    cmds:
      - apt update
      - apt install -y --allow-downgrades rsync vlc mpv
