version: '3'

tasks:
  install-desktop:
    cmds:
    - task: update
    - task: cli-dependencies
    - task: desktop-dependencies
    - task: clean
  install-cli:
    cmds:
    - task: update
    - task: cli-dependencies
    - task: clean
  update:
    cmds:
      - apt update
      - apt dist-upgrade -y --allow-downgrades
  cli-dependencies:
    cmds:
      - apt update
      - apt install -y --allow-downgrades rsync ffmpeg
  desktop-dependencies:
    cmds:
      - apt update
      - apt install -y --allow-downgrades vlc mpv
  clean:
    cmds:
      - apt autoremove -y
      - apt autoclean