version: '3'

tasks:
  update:
    cmds:
      - apt update
      - apt dist-upgrade -y
  dependencies:
    cmds:
      - apt update
      - apt install -y rsync vlc mpv
  install:
    cmds:
    - task: update
    - task: dependencies